import type { Subscription as DBSubscription } from "@/lib/supabase/subscriptions";

export const initialSubscriptions: DBSubscription[] = [
    {
        id: 1,
        name: "ChatGPT Plus",
        category: "AI Tools",
        price: 20,
        icon: "🤖",
        renews_in: 5,
        status: "active",
        color: "#10A37F",
        renewal_url: "https://platform.openai.com/account/billing/overview",
        tags: ["ai", "chat"],
        date_added: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        last_used_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        has_api_key: true,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 2,
        name: "Netflix",
        category: "Streaming",
        price: 15.49,
        icon: "🎬",
        renews_in: 12,
        status: "active",
        color: "#E50914",
        renewal_url: "https://www.netflix.com/account",
        tags: ["streaming", "entertainment"],
        date_added: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 3,
        name: "Spotify Premium",
        category: "Streaming",
        price: 10.99,
        icon: "🎵",
        renews_in: 8,
        status: "active",
        color: "#1DB954",
        renewal_url: "https://www.spotify.com/account/subscription/",
        tags: ["streaming", "music"],
        date_added: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 4,
        name: "Notion",
        category: "Productivity",
        price: 10,
        icon: "📝",
        renews_in: 15,
        status: "active",
        color: "#000000",
        renewal_url: "https://www.notion.so/account/settings",
        tags: ["productivity", "notes"],
        date_added: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 5,
        name: "Adobe Creative Cloud",
        category: "Design",
        price: 54.99,
        icon: "🎨",
        renews_in: 20,
        status: "active",
        color: "#FF0000",
        renewal_url: "https://account.adobe.com/plans",
        tags: ["design", "creative"],
        date_added: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 6,
        name: "GitHub Copilot",
        category: "AI Tools",
        price: 10,
        icon: "👨‍💻",
        renews_in: 5,
        status: "trial",
        color: "#000000",
        renewal_url: "https://github.com/settings/billing/summary",
        tags: ["ai", "code", "development"],
        date_added: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        last_used_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        has_api_key: false,
        is_trial: true,
        trial_ends_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        price_after_trial: 10,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 7,
        name: "Midjourney",
        category: "AI Tools",
        price: 30,
        icon: "🖼️",
        renews_in: 10,
        status: "active",
        color: "#000000",
        renewal_url: "https://www.midjourney.com/account/billing/manage",
        tags: ["ai", "image", "creative"],
        date_added: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        last_used_at: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        has_api_key: true,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 8,
        name: "Microsoft 365",
        category: "Productivity",
        price: 6.99,
        icon: "💼",
        renews_in: 25,
        status: "active",
        color: "#0078D4",
        renewal_url: "https://account.microsoft.com/services/",
        tags: ["productivity", "office"],
        date_added: new Date(Date.now() - 300 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 9,
        name: "Disney+",
        category: "Streaming",
        price: 7.99,
        icon: "🏰",
        renews_in: 18,
        status: "active",
        color: "#113CCF",
        renewal_url: "https://www.disneyplus.com/account",
        tags: ["streaming", "entertainment"],
        date_added: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 10,
        name: "Figma Professional",
        category: "Design",
        price: 12,
        icon: "🎯",
        renews_in: 7,
        status: "trial",
        color: "#F24E1E",
        renewal_url: "https://www.figma.com/settings",
        tags: ["design", "ui", "collaboration"],
        date_added: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        is_trial: true,
        trial_ends_at: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        price_after_trial: 12,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 11,
        name: "Vercel Pro",
        category: "Development",
        price: 20,
        icon: "▲",
        renews_in: 3,
        status: "cancelled",
        color: "#000000",
        renewal_url: "https://vercel.com/account/billing",
        tags: ["development", "hosting"],
        date_added: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        is_trial: false,
        source: "manual",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "variable",
        price_range: { min: 15, max: 50 },
        price_history: [
            {
                date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
                amount: 18,
            },
            {
                date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
                amount: 22,
            },
            {
                date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
                amount: 20,
            },
        ],
        billing_cycle: "monthly",
        cancelled_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        active_until: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 13,
        name: "ChatGPT Plus",
        category: "AI Tools",
        price: 20,
        icon: "🤖",
        renews_in: 8,
        status: "active",
        color: "#10A37F",
        renewal_url: "https://platform.openai.com/account/billing/overview",
        tags: ["ai", "chat"],
        date_added: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 2,
        last_used_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        has_api_key: true,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
    },
    {
        id: 14,
        name: "Spotify Premium",
        category: "Streaming",
        price: 10.99,
        icon: "🎵",
        renews_in: 0,
        status: "paused",
        color: "#1DB954",
        renewal_url: "https://www.spotify.com/account/subscription/",
        tags: ["streaming", "music"],
        date_added: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        is_trial: false,
        source: "auto_detected",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "monthly",
        paused_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        resumes_at: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 15,
        name: "Notion Lifetime",
        category: "Productivity",
        price: 299,
        icon: "📝",
        renews_in: null,
        status: "active",
        color: "#000000",
        renewal_url: null,
        tags: ["productivity", "notes"],
        date_added: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
        email_account_id: 1,
        is_trial: false,
        source: "manual",
        manually_edited: false,
        edited_fields: [],
        pricing_type: "fixed",
        billing_cycle: "lifetime",
    },
];

export const initialEmailAccounts = [
    {
        id: 1,
        email: "caleb@gmail.com",
        provider: "gmail",
        isPrimary: true,
        connectedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
        lastScanned: new Date(Date.now() - 2 * 60 * 1000),
        subscriptionCount: 4,
    },
    {
        id: 2,
        email: "caleb.work@company.com",
        provider: "gmail",
        isPrimary: false,
        connectedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        lastScanned: new Date(Date.now() - 5 * 60 * 1000),
        subscriptionCount: 2,
    },
];

